# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c97ef875da95151c8973de8cccc428f123b680ada3d9a56e4dd874c401cd180bdd2b3eee415bc436f2f61804b2434b3f76fa92624f4bb361ee86792c7bcd807f

test:
  secret_key_base: 4d4101f61f43b8d09e2b912b8087cfef2612d43e2b3e1bf9557f1787781f4da7ce4d9ac7eadd9dd319331132750dc292b0821ea79d546ff0acc4aac05c4e2c75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
